### PR TITLE
Science pack 6 - replace coal with charcoal when SeaBlock mod is used

### PR DESCRIPTION
**Pull request by domis86**
Because no coal in SeaBlock :/

### CODE REVIEW

**Review by ByteSquire — DISMISSED** [review]
I noticed that you are using bobmods.lib

Therefore we'd need to add the boblibrary mod as a dependency, right?

**Comment by domis86** [comment]
> I noticed that you are using bobmods.lib
> 
> Therefore we'd need to add the boblibrary mod as a dependency, right?

@ByteSquire good point. 

I assumed is already added because it was already used as you can see here: https://github.com/ByteSquire/factorio-mods/blob/main/MoreSciencePacks-for1_1/prototypes/recipe/recipe-corrections.lua#L26-L27

Adding 👍

**Comment by ByteSquire** [comment]
> > I noticed that you are using bobmods.lib
> > Therefore we'd need to add the boblibrary mod as a dependency, right?
> 
> @ByteSquire good point.
> 
> I assumed is already added because it was already used as you can see here: https://github.com/ByteSquire/factorio-mods/blob/main/MoreSciencePacks-for1_1/prototypes/recipe/recipe-corrections.lua#L26-L27
> 
> Adding 👍

@domis86 yeah, same here.
the boblogistics mod also already depends on the boblibrary...so I'd say leave it as it is
there's even a comment right there talking about the topic 😄

**Comment by domis86** [comment]
indeed - lets leave it 👍  🙂

**Pull request merged**
